  
apiVersion: v1
kind: ConfigMap
metadata:
  name: petc-configmap
data:
  # all the environment variables related to mysql from readme file
  mysql_root_password: ""
  mysql_allow_empty_password: "true"
  mysql_user: petc
  mysql_password: petc
  mysql_database: petc