apiVersion: v1
kind: Service 
metadata:
  name: petc-service
spec:
  selector:
    app: petc # the same label we used for the petclinic deployment
  type: NodePort # connect with the pod 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080